import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
const read=path=>readFileSync(new URL('../'+path,import.meta.url),'utf8');
const html=read('studio.html'),js=read('studio.js'),css=read('studio.css');
execFileSync(process.execPath,['--check',new URL('../studio.js',import.meta.url).pathname]);
const source=(from,to,symbol)=>{
 const a=js.indexOf(from),b=js.indexOf(to,a+from.length);
 assert(a>=0&&b>=0,'Missing '+symbol+' source segment');
 return new Function(js.slice(a,b)+';return '+symbol)();
};
const csv=source('function parseCsv(','async function importFile(','parseCsv');
const col=source('function findColumn(','function mapColumns(','findColumn');
const ai=source('function parseAIResponse(','async function reviewBatch(','parseAIResponse');
const input=source('function parseChannelInput(','async function yt(','parseChannelInput');
const safeCsv=source('function csvCell(','function buildReviewTable(','csvCell');
assert.deepEqual(csv('Date,Old Title,New Title\n2026-10-09,"One, two","Title ""A"""')[1],
 ['2026-10-09','One, two','Title "A"']);
assert.deepEqual(csv('Old,New\n"first\nline",second')[1],['first\nline','second']);
assert.throws(()=>csv('old,"broken'),/unmatched/);
assert.equal(col(['Date','Old Title','New Title','Notes'],'date'),0);
assert.equal(col(['Date','Old Title','New Title','Notes'],'old'),1);
assert.equal(col(['Date','Old Title','New Title','Notes'],'new'),2);
assert.equal(col(['ਮਿਤੀ','ਪੁਰਾਣਾ ਟਾਈਟਲ','ਨਵਾਂ ਟਾਈਟਲ'],'old'),1);
assert.equal(input('@rojanabhaktii').forHandle,'@rojanabhaktii');
assert.equal(input('UCX6OQ3DkcsbYNE6H8uQQuVA').id,'UCX6OQ3DkcsbYNE6H8uQQuVA');
assert.throws(()=>input('https://example.com/@someone'),/YouTube channel URL/);
assert.equal(ai('{"reviews":[{"id":1,"decision":"keep"}]}').reviews[0].id,1);
assert.equal(ai('```json\n{"reviews":[]}\n```').reviews.length,0);
assert.throws(()=>ai('invalid'),/parseable review JSON/);
assert.equal(safeCsv('=HYPERLINK(1)'), '"\'=HYPERLINK(1)"');
assert.equal(safeCsv('one"two'),'"one""two"');
const refs=[...js.matchAll(/\$\('([A-Za-z0-9]+)'\)/g)].map(m=>m[1]);
const ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);
const dynamicIds=new Set(['finalTitleInput']);
assert.deepEqual([...new Set(refs)].filter(id=>!ids.includes(id)&&!dynamicIds.has(id)),[]);
assert.equal(ids.length,new Set(ids).size,'Duplicated studio HTML IDs');
assert(html.includes('xlsx-0.20.3/package/dist/xlsx.full.min.js'),'Versioned official Excel parser missing');
assert(html.includes('studio.js')&&html.includes('studio.css'),'Studio assets not loaded');
assert(css.includes('@media(max-width:760px)'),'Mobile responsive layout missing');
assert(js.includes('responseMimeType:\'application/json\''),'AI structured output missing');
assert(js.includes('snapshotToPublic('),'Real public YouTube facts missing');
assert(!/AIza[0-9A-Za-z_-]{20,}/.test(js),'API secret in browser source');
console.log('Content Studio checks passed: JS syntax, CSV edge cases, bilingual mapping, AI JSON, safe export, channel input, assets and DOM references.');
